version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: "docker/django/Dockerfile"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app

  celery:
    build:
      context: .
      dockerfile: "docker/celery/Dockerfile"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
  
  celery_flower: 
    build:
      context: .
      dockerfile: "docker/celery_flower/Dockerfile"
    depends_on:
        - redis
        - celery
        
    volumes:
      - .:/app
    ports:
      - "5555:5555"




  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
