# Generated by Django 5.1.4 on 2025-01-07 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Compose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('personal', 'Personal Domain'), ('ses', 'Amazon SES')], default='gmail', max_length=50)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('use_tls', models.BooleanField(blank=True, default=True, null=True)),
                ('use_ssl', models.BooleanField(blank=True, default=False, null=True)),
                ('aws_access_key_id', models.CharField(blank=True, max_length=255, null=True)),
                ('aws_secret_access_key', models.CharField(blank=True, max_length=255, null=True)),
                ('aws_region', models.CharField(blank=True, max_length=50, null=True)),
                ('ses_configuration_set', models.CharField(blank=True, max_length=255, null=True)),
                ('iam_role_arn', models.CharField(blank=True, max_length=255, null=True)),
                ('enable_tracking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_compose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.email_compose')),
            ],
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=50)),
                ('failed_reason', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_compose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.email_compose')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=50)),
                ('failed_reason', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_compose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.email_compose')),
            ],
        ),
        migrations.AddField(
            model_name='email_compose',
            name='configurations',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.smtpconfiguration'),
        ),
    ]
