# Generated by Django 5.1.4 on 2025-01-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_alter_email_compose_configurations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachmentsFiles/'),
        ),
        migrations.AlterField(
            model_name='smtpconfiguration',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smtpconfiguration',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smtpconfiguration',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
