# Generated by Django 5.1.4 on 2025-01-08 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_attachment_file_alter_smtpconfiguration_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_compose',
            name='configurations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.smtpconfiguration'),
        ),
    ]
